Added Mac OS support, added helper classes, added SDO extension
Apollo3zehn/EtherCAT.NET pull request #53
Opened 2021-02-05 10:02 UTC by XzuluX

Please especially check the modification in EcMaster.cs, I think the ioMapBitOffset should be set to zero if the IO mapping byte offset changes.

2021-02-12 17:08 UTC, Apollo3zehn requested changes
Looks good so far (I have changed only minor things).
Two questions remain:
- Why does DigitalOut inherit from DigitalIn? That means every digital out slave has a `GetChannel` method but digital in slaves do not have a `SetChannel` method. This seems to be inconsistent for me.
- You added OSX support but did not change SOEM.PInvoke.csproj to create a proper Nuget .nupkg file. However, integrating OSX support would require much more work because the CI provider AppVeyor does not offer OSX images. So the only solution would be to use Travis CI for this, wait for it to complete and then build the *.nupkg containing all the OS native files. I did this once for the HDF.PInvoke project but I would like to avoid this here until there is a real demand for OSX. What do you think?

2021-02-12 19:51 UTC, XzuluX commented
> Looks good so far (I have changed only minor things).
> Two questions remain:

Thank's for reviewing my PR !
> 
>     * Why does DigitalOut inherit from DigitalIn? That means every digital out slave has a `GetChannel` method but digital in slaves do not have a `SetChannel` method. This seems to be inconsistent for me.

- Intention was  to provide digital in slaves with `GetChannel` method in order to query whether an input is set, they don't have outputs, so `SetChannel` makes not really sense. Digital out slaves should set output with `SetChannel` and the purpose of `GetChannel` is to query the output state. I choosed inheritance to avoid code duplication for class members.


>     * You added OSX support but did not change SOEM.PInvoke.csproj to create a proper Nuget .nupkg file. However, integrating OSX support would require much more work because the CI provider AppVeyor does not offer OSX images. So the only solution would be to use Travis CI for this, wait for it to complete and then build the *.nupkg containing all the OS native files. I did this once for the HDF.PInvoke.1.10 project but I would like to avoid this here until there is a real demand for OSX. What do you think?

- My PR comment is a little bit misleading, main intention was to enable build on OSX. Up to now it's not really necessary to have nupkg for OSX.

2021-02-12 20:48 UTC, Apollo3zehn commented
Thanks, I'll check your changes to the master (reset of bit offset) against SOEM source code on Monday. I think the changes make sense but I have to check it once. After that I can merge your PR.

2021-02-16 08:11 UTC, Apollo3zehn approved these changes

2021-02-16 08:11 UTC, merged